#sudo: false
# travis-ci.org build & test configuration
language: python

matrix:
    include:
        - python: 3.6
        - python: 3.7
        - python: 3.8
    allow_failures:

install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then curl --silent http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -o miniconda.sh; fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi

  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --set show_channel_urls yes
  - conda create -q -n testenv python=${TRAVIS_PYTHON_VERSION%-*}
  - export CONDA_ENV_PATH=$HOME/miniconda/envs/testenv
  - source activate testenv
  - python setup.py -q install
  - pip install -r requirements/test.txt

script:
  - pytest --cov

after_success:
  - coverage combine
  - codecov

cache: apt

deploy:
  provider: pypi
  user: tai.sakuma
  distributions: sdist bdist_wheel --universal
  password:
    secure: lsFXZu2nOw0K3UGyHIGm8NPLB68xNOTOrjt4q3IDN8bpZgXK9kCvqyzsfjbQJm++lOTmn6U8Gy56KntrYTfeTEimFNvO9EXEZW+vW6LBiv9fuk5es2v3g7fqI9Ogb78OF4o2DX6Yei68OIWq/5bkcko1zwui0P72daeZX9EE9xgmFW152hoDjk4Pdreke2duPoS/151TcDo/jSpLg3chqidEyd2s7m+kijhUESVto9Jw1U+XeIhuk1vo8Qs58UmFFp5BxR0bAa3XOrS6opb04EFAzhLIe7o/Gqhlax9vn3en8Zl9ETZNeeGwYXGuQ18ojWBb5DGvzD+qZFyqvJmb9WLgSBlxSgji503EW+ldaZsNYT25A82z4PnzXtrDyyMS70ofzw8YdD4c17M6zHpnY+kONjUOCLBG9XDKt5W8Ar5Og7wT6VD32fIT1e/h4oeLSDe59k6g1PtsaqRZpdB84HLTNTlU87TLCfcW22ScWSCqTY1oFbIUDgzkvPPKLBGccDb2oeneMSfCt5ZZD/vcyuKqiK4R+k4k/OcQCH2TztAsSQ1WbM1z+qsPZwOjK6S1HMtZQpUNVs6s3LFVwuWH65ZXuwAaVOw6S3mqsvdA/egr1XuzLTdCagEM3rdXCABEJXyDpznAcVx910+U0IQFyPegTiH3QYb2DAUJ0X8m5wA=
  on:
    tags: true
    python: 3.7
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
